export interface TechStackItem {
  id: string;
  name: string;
  version: string;
  category: string;
  description: string;
  icon?: string;
  url?: string;
}

export const techStackData: TechStackItem[] = [
  {
    id: 'nextjs',
    name: 'Next.js',
    version: '15.1.6',
    category: 'core',
    description: '',
    url: 'https://nextjs.org',
  },
  {
    id: 'react',
    name: 'React',
    version: '19.0.0',
    category: 'core',
    description: '',
    url: 'https://react.dev',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    version: '5.8.2',
    category: 'core',
    description: '',
    url: 'https://typescriptlang.org',
  },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    version: '4.0.0',
    category: 'ui',
    description: '',
    url: 'https://tailwindcss.com',
  },
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui',
    version: 'latest',
    category: 'ui',
    description: '',
    url: 'https://ui.shadcn.com',
  },
  {
    id: 'radix-ui',
    name: 'Radix UI',
    version: 'latest',
    category: 'ui',
    description: '',
    url: 'https://radix-ui.com',
  },
  {
    id: 'next-intl',
    name: 'next-intl',
    version: '3.29.1',
    category: 'i18n',
    description: '',
    url: 'https://next-intl.dev',
  },
  {
    id: 'eslint',
    name: 'ESLint',
    version: '9.18.0',
    category: 'tools',
    description: '',
    url: 'https://eslint.org',
  },
  {
    id: 'prettier',
    name: 'Prettier',
    version: '3.4.2',
    category: 'tools',
    description: '',
    url: 'https://prettier.io',
  },
  {
    id: 'husky',
    name: 'Husky',
    version: '9.1.7',
    category: 'tools',
    description: '',
    url: 'https://typicode.github.io/husky',
  },
  {
    id: 'jest',
    name: 'Jest',
    version: '29.7.0',
    category: 'testing',
    description: '',
    url: 'https://jestjs.io',
  },
  {
    id: 'testing-library',
    name: 'Testing Library',
    version: '16.1.0',
    category: 'testing',
    description: '',
    url: 'https://testing-library.com',
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    version: '10.13.1',
    category: 'dev',
    description: '',
    url: 'https://pnpm.io',
  },
  {
    id: 'turbo',
    name: 'Turbo',
    version: '2.3.3',
    category: 'dev',
    description: '',
    url: 'https://turbo.build',
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    version: 'latest',
    category: 'performance',
    description: '',
    url: 'https://developers.google.com/web/tools/lighthouse',
  },
  {
    id: 'semgrep',
    name: 'Semgrep',
    version: 'latest',
    category: 'security',
    description: '',
    url: 'https://semgrep.dev',
  },
  {
    id: 'embla-carousel',
    name: 'Embla Carousel',
    version: '8.6.0',
    category: 'animation',
    description: '',
    url: 'https://embla-carousel.com',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    version: 'latest',
    category: 'deployment',
    description: '',
    url: 'https://vercel.com',
  },
  {
    id: 'sonarqube',
    name: 'SonarQube',
    version: 'latest',
    category: 'quality',
    description: '',
    url: 'https://sonarqube.org',
  },
  {
    id: 'storybook',
    name: 'Storybook',
    version: '8.4.7',
    category: 'docs',
    description: '',
    url: 'https://storybook.js.org',
  },
  {
    id: 'swr',
    name: 'SWR',
    version: '2.3.0',
    category: 'data',
    description: '',
    url: 'https://swr.vercel.app',
  },
  {
    id: 'zustand',
    name: 'Zustand',
    version: '5.0.2',
    category: 'state',
    description: '',
    url: 'https://zustand.docs.pmnd.rs',
  },
];

export const techStackCategories = Object.freeze({
  core: 'core',
  ui: 'ui',
  i18n: 'i18n',
  tools: 'tools',
  testing: 'testing',
  dev: 'dev',
  performance: 'performance',
  security: 'security',
  animation: 'animation',
  deployment: 'deployment',
  quality: 'quality',
  docs: 'docs',
  data: 'data',
  state: 'state',
} as const);

export type TechStackCategory = keyof typeof techStackCategories;
